name: spography_trivial
description: "App basada en un mapa interactivo con datos de los paises y quiz de preguntas."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  cloud_firestore: ^6.1.2
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_native_splash:
  color: "#121212"  
  image: assets/logo_spography.png
  android_12:
    image: assets/logo_spography.png
    color: "#121212"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo_spography.png"
  min_sdk_android: 21
  adaptive_icon_background: "#121212"
  adaptive_icon_foreground: "assets/logo_spography.png"